### ISSUE TITLE
Click on JIRA-Tab results in error warning 

### ISSUE THREAD

**Issue by SIEDA-MiTra** [kayako/jira-integration#11]
Kayako ticket was linked with JIRA Issue.
Click on JIRA-Tab in Kayako results in following error warning:

**Warning**
preg_match(): Unknown modifier 'P' (./__apps/jira/library/JIRA/class.SWIFT_JIRAComment.php:139)
![kayako_failure](https://cloud.githubusercontent.com/assets/15910273/11244983/caa1a40a-8e10-11e5-868c-b34dac6a9926.png)

**Comment by SIEDA-MiTra** [comment]
can you help @ravi-sharma ?

**Comment by gurpreetburmi31** [comment]
Hi @SIEDA-MiTra, 

Can you please let us know the PHP version installed on your server ? We have tried to re-create the same problem at our end, no luck. 

You may also raise a support ticket with us at https://support.kayako.com/ with your Kayako and JIRA details. We will look into the issue and help you out. 

Gurpreet

**Comment by SIEDA-MiTra** [comment]
Hi @gurpreetburmi31,
sorry for late replay.

Background: I'm working in our development department and administrate JIRA. I Have only little to do with helpdesk service (KAYAKO). So in the end, for every Information I have to aks other people.

Back to the failure ... packages installed on your KAYAKO server:
Apache2
php5.5
mysql 5
ufw

To be precise: PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)

Thanks for your help.
Michael

**Comment by gurpreetburmi31** [comment]
Hi @SIEDA-MiTra, 

Please raise a support ticket with your Kayako and JIRA details, we will look into it. 

Regards,
Gurpreet

**Comment by SIEDA-MiTra** [comment]
Hi @gurpreetburmi31,

Kayako support ticket was raised by one of my colleagues.

Ticket ID: TRG-335-98455
You can check the status of or update this ticket online at: https://support.kayako.com/index.php?/Tickets/Ticket/View/TRG-335-98455

Regards
Michael

**Comment by SIEDA-MiTra** [comment]
Problem was solved by KAYAKO Support.
Resolution is confirmed.

**Comment by gurpreetburmi31** [comment]
@SIEDA-MiTra Glad to know that w were able to resolve it for you. 

Happy Helpdesking!!
