### ISSUE TITLE
JIRA info for Ticket (Tab) broken / error for existing ticket links since JIRA upgrade to 7.1.1

### ISSUE THREAD

**Issue by estos-it** [kayako/jira-integration#16]
Hello,

since upgrade from JIRA 6 to JIRA Software 7.1.1 we get an error on existing ticket links in Kayako when opening the "JIRA" Tab:
```

> Warning
> preg_match(): Unknown modifier 'M' (./__apps/jira/library/JIRA/class.SWIFT_JIRAComment.php:139)
> =================================================================================================================================
> 

```

If we create a new link (existing or new JIRA ticket), everything works as expected.

Can you provide any hint or help?

Thank you.

**Comment by SIEDA-MiTra** [comment]
We've got nearly the same message with JIRA 6.4 when we're just startet the kayako jira-integration.
See #11

**Comment by gurpreetburmi31** [comment]
This issue has been resolved.

**Comment by estos-it** [comment]
Thank you for the quick help!
