### ISSUE TITLE
Installation on Fusion Version	4.68.1

### ISSUE THREAD

**Issue by codexdev** [kayako/jira-integration#9]
I get immediate error when trying to install jira-integration plugin.

`Exception13 October 2015 10:11 PM (7m 24s)
Router: http://helpdesk.printxinc.com/admin/index.php?/Base/App/Install/jira-integration-master
Uncaught Exception: Invalid data provided in ./__swift/library/App/class.SWIFT_App.php:954

#0 /var/www/helpdesk.printxinc.com/public_html/__swift/library/App/class.SWIFT_AppManager.php(122): SWIFT_App::RetrieveSetupDatabaseObject('jira-integratio...')
#1 /var/www/helpdesk.printxinc.com/public_html/__swift/apps/base/admin/class.Controller_App.php(128): SWIFT_AppManager::Install('jira-integratio...')
#2 [internal function]: Controller_App-&gt;Install('jira-integratio...')
#3 /var/www/helpdesk.printxinc.com/public_html/__swift/library/MVC/class.SWIFT_Controller.php(371): call_user_func_array(Array, Array)
#4 /var/www/helpdesk.printxinc.com/public_html/__swift/library/App/class.SWIFT_App.php(176): SWIFT_Controller::Load(Object(SWIFT_Interface), Object(SWIFT_App), Object(SWIFT_Router), false)
#5 /var/www/helpdesk.printxinc.com/public_html/__swift/library/class.SWIFT.php(294): SWIFT_App-&gt;ExecuteController(Object(SWIFT_Router))
#6 /var/www/helpdesk.printxinc.com/public_html/__swift/library/class.SWIFT.php(396): SWIFT-&gt;Initialize()
#7 /var/www/helpdesk.printxinc.com/public_html/__swift/swift.php(124): SWIFT::GetInstance()
#8 /var/www/helpdesk.printxinc.com/public_html/admin/index.php(29): require_once('/var/www/helpde...')
#9 {main}`

**Comment by ravi-sharma** [comment]
Please rename the src folder to jira and make sure all files of src folder are available under __apps/jira
